version: '3.7'
services:
  alfa:
    build: .
    ports:
    - "8082:8080"
    restart: always
  database:
    build: ./db
    volumes:
    - database-data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: alfa_battle
      POSTGRES_USER: alfa_battle
      POSTGRES_PASSWORD: qwe123

volumes:
  database-data: {}
